wallpaper {
    monitor = HDMI-A-1
    path = ~/.dotfiles/wallpapers/sunflowers.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/.dotfiles/wallpapers/sunflowers_9x16.png
    fit_mode = cover
}

splash = false
ipc = false
