$font = JetBrainsMono Nerd Font

general {
  disable_loading_bar = true
  hide_cursor = true
}

background {
  monitor =
  path = ~/.dotfiles/wallpapers/sunflowers.png
  blur_passes = 3
  blur_size = 6
  color = rgb(9292F9)
}

label {
  monitor =
  text = cmd[update:1000] date +"%A, %B %d"
  color = rgba(d2dcd9, 0.75)
  font_size = 22
  font_family = $font
  position = 0, 300
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] date +"%-H:%M"
  color = rgba(d2dcd9, 0.75)
  font_size = 95
  font_family = $font Extrabold
  position = 0, 200
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 250, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true

  outer_color = rgba(0, 0, 0, 0)
  inner_color = rgb(0F1114)

  font_color = rgb(d2dcd9)

  fade_on_empty = false

  shadow_passes = 4
  shadow_size = 3
  shadow_color = rgb(0F1114)

  placeholder_text = 󰌾 Logged in as $USER

  check_color = rgb(0F1114)
  fail_color = rgb(566163)
  fail_text = $FAIL ($ATTEMPTS)

  capslock_color = rgb(5BB0BB)

  position = 0, 0
  halign = center
  valign = center
}
